### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by Diegovsky** [RandomChisk/NoMoreYoutubeShorts#1] opened 2022-03-23 02:24 UTC
I have no idea how to make an extension otherwise I would open a PR :(

**Comment by RandomChisk** [comment] 2022-03-24 09:07
Went through some converting progress, and it's here now! Check out the releases tab. (Worked perfectly on both Firefox dev edition and normal Firefox 98.0.2)

I'll close this issue if you can confirm that the extension works on your Firefox too. Thanks!

**Comment by Diegovsky** [comment] 2022-03-24 20:07
I just tested it. It seems that youtube does some trickery that if I load a video (from the homepage, but likely from anywhere in the site), the extension does not work. However, if reload the page, it works perfectly!

Thank you so much for porting it to firefox btw :D

**Comment by RandomChisk** [comment] 2022-03-25 05:30
Yeah, YouTube uses some weird way to navigate between pages, so the extension can't really detect if the page has been changed unless you reload/open as a new tab.
Anyway, glad to hear that my extension works as intended!

**Closed as completed by RandomChisk** 2022-03-25 05:30 UTC
Labels: enhancement

**Comment by Diegovsky** [comment] 2022-03-26 16:22
Thank you so much :D
